import Rhino.Geometry as rg

def create_rebarShapeCurve_in_rhino(name,plane=None,a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,x=0,y=0,j=0):
    if name=="rg01":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg02":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg03":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg04":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg05":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg06":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg07":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg08":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg09":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg10":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg11":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg12":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg13":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg14":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg15":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg16":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg17":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))
    elif name=="rg18":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,1000,0))
    elif name=="rg19":
        return rg.Line(rg.Point3d(0,0,0),rg.Point3d(1000,0,0))